import { contextBridge, ipcRenderer } from 'electron';
import type { HubAPI } from '../src/shared/types';
const api: HubAPI = {
  getTradeContext:(cardId,items)=>ipcRenderer.invoke('hub:trade-context',cardId,items),
  previewOrder:input=>ipcRenderer.invoke('hub:trade-preview',input),
  submitOrder:input=>ipcRenderer.invoke('hub:trade-submit',input),
  getTradeAttempts:()=>ipcRenderer.invoke('hub:trade-attempts'),
  queryTradeAttempt:id=>ipcRenderer.invoke('hub:trade-query',id),
  openTradeAgreement:(id,index)=>ipcRenderer.invoke('hub:trade-agreement',id,index),
  getViewState: () => ipcRenderer.invoke('hub:view-state'),
  queryProducts: query=>ipcRenderer.invoke('hub:query-products',query),
  getProduct:id=>ipcRenderer.invoke('hub:product',id),
  queryOrders:query=>ipcRenderer.invoke('hub:query-orders',query),
  exportOrders:query=>ipcRenderer.invoke('hub:export-orders',query),
  getSyncTasks:()=>ipcRenderer.invoke('hub:sync-tasks'),
  cancelSync:id=>ipcRenderer.invoke('hub:cancel-sync',id),
  retryFailedSync:()=>ipcRenderer.invoke('hub:retry-sync'),
  onSyncTasks:callback=>{const listener=(_:unknown,tasks:Parameters<typeof callback>[0])=>callback(tasks);ipcRenderer.on('hub:sync-tasks',listener);return()=>ipcRenderer.removeListener('hub:sync-tasks',listener);},
  getPriceHistory:(id,sourceId)=>ipcRenderer.invoke('hub:price-history',id,sourceId),
  checkUpdates:()=>ipcRenderer.invoke('hub:check-updates'),
  openUpdate:()=>ipcRenderer.invoke('hub:open-update'),
  prepareUpdate:()=>ipcRenderer.invoke('hub:prepare-update'),
  cancelUpdate:()=>ipcRenderer.invoke('hub:cancel-update'),
  installUpdate:()=>ipcRenderer.invoke('hub:install-update'),
  onUpdateProgress:callback=>{const listener=(_:unknown,value:Parameters<typeof callback>[0])=>callback(value);ipcRenderer.on('hub:update-progress',listener);return()=>ipcRenderer.removeListener('hub:update-progress',listener);},
  getAddresses: () => ipcRenderer.invoke('hub:addresses'),
  saveAddress: (draft,id) => ipcRenderer.invoke('hub:save-address',draft,id),
  setDefaultAddress: id => ipcRenderer.invoke('hub:default-address',id),
  removeAddress: id => ipcRenderer.invoke('hub:remove-address',id),
  exportAddresses: passphrase => ipcRenderer.invoke('hub:export-addresses',passphrase),
  importAddresses: passphrase => ipcRenderer.invoke('hub:import-addresses',passphrase),
  getAddressRegions: parentId => ipcRenderer.invoke('hub:address-regions',parentId),
  getOfficialAddresses: cardId => ipcRenderer.invoke('hub:official-addresses',cardId),
  publishAddress: (cardId,localId,makeDefault) => ipcRenderer.invoke('hub:publish-address',cardId,localId,makeDefault),
  getState: () => ipcRenderer.invoke('hub:state'),
  addCards: (cards) => ipcRenderer.invoke('hub:add-cards', cards),
  updateCard: (id, patch) => ipcRenderer.invoke('hub:update-card', id, patch),
  openCard: (id, purpose) => ipcRenderer.invoke('hub:open-card', id, purpose),
  openProduct: (productId, cardId, sourceId) => ipcRenderer.invoke('hub:open-product', productId, cardId, sourceId),
  syncCard: (id) => ipcRenderer.invoke('hub:sync-card', id),
  syncAll: () => ipcRenderer.invoke('hub:sync-all'),
  favoriteProduct: (id) => ipcRenderer.invoke('hub:favorite', id),
  mergeProducts: (ids) => ipcRenderer.invoke('hub:merge', ids),
  addToCart: (productId, cardId, quantity, sourceId) => ipcRenderer.invoke('hub:add-cart', productId, cardId, quantity, sourceId),
  updateCart: (id, quantity) => ipcRenderer.invoke('hub:update-cart', id, quantity),
  checkout: (cardId) => ipcRenderer.invoke('hub:checkout', cardId),
  updateSettings: (settings) => ipcRenderer.invoke('hub:settings', settings),
  exportData: (passphrase) => ipcRenderer.invoke('hub:export', passphrase),
  importData: (passphrase) => ipcRenderer.invoke('hub:import', passphrase),
  openDataFolder: () => ipcRenderer.invoke('hub:data-folder'),
  exportDiagnostics: () => ipcRenderer.invoke('hub:diagnostics'),
  onState: (callback) => { let sequence=0,active=true;const listener=()=>{const ticket=++sequence;void api.getViewState().then(state=>{if(active&&ticket===sequence)callback(state);}).catch(()=>{});};ipcRenderer.on('hub:invalidated',listener);return()=>{active=false;ipcRenderer.removeListener('hub:invalidated',listener);}; }
};
contextBridge.exposeInMainWorld('hub', api);
