import { build,Platform,Arch } from 'electron-builder';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync,writeFileSync } from 'node:fs';
import { basename,resolve } from 'node:path';
import { artifactManifest,versionNotes } from './release-metadata.mjs';

const platform=process.argv[2];
if(!['win','mac'].includes(platform))throw new Error('Usage: node scripts/build-release.mjs win|mac [--signed]');
const signed=process.argv.includes('--signed')||process.env.REQUIRE_SIGNED==='true';
if(signed&&platform==='win'&&!process.env.WIN_CSC_LINK&&!process.env.CSC_LINK)throw new Error('Signed Windows release requires WIN_CSC_LINK and WIN_CSC_KEY_PASSWORD in the environment.');
if(signed&&platform==='mac'&&!process.env.CSC_LINK&&!process.env.CSC_NAME)throw new Error('Signed macOS release requires CSC_LINK/CSC_KEY_PASSWORD or CSC_NAME in the environment.');
const pkg=JSON.parse(readFileSync('package.json','utf8'));
const archIndex=process.argv.indexOf('--arch'),arch=archIndex<0?process.arch:process.argv[archIndex+1];
if(!['x64','arm64'].includes(arch))throw new Error('Supported architectures: x64, arm64');
if(platform==='win'&&arch!=='x64')throw new Error('Windows release currently supports x64');
const repo=process.env.GITHUB_REPOSITORY??pkg.repository?.url?.match(/github\.com\/([^/]+\/[^/]+?)(?:\.git)?$/)?.[1];
const base=process.env.RELEASE_BASE_URL??(repo?`https://github.com/${repo}/releases/download/v${pkg.version}/`:undefined);
if(!base)throw new Error('A repository or RELEASE_BASE_URL is required');
// Run the same build stages with Node directly; Windows command scripts need no shell.
execFileSync(process.execPath,[resolve('node_modules/typescript/bin/tsc'),'--noEmit'],{stdio:'inherit'});
execFileSync(process.execPath,[resolve('node_modules/vite/bin/vite.js'),'build'],{stdio:'inherit'});
execFileSync(process.execPath,[resolve('scripts/build-electron.mjs')],{stdio:'inherit'});
const files=await build({targets:(platform==='win'?Platform.WINDOWS:Platform.MAC).createTarget(platform==='win'?'nsis':'zip',Arch[arch]),publish:'never',config:{forceCodeSigning:signed,...(platform==='mac'?{mac:{target:'zip',artifactName:`guanaitong-hub-${pkg.version}-${arch}.zip`}}:{})}});
const assets=files.filter(path=>platform==='win'?path.endsWith('.exe'):path.endsWith('.zip'));
const checksums=assets.map(path=>({path,sha256:createHash('sha256').update(readFileSync(path)).digest('hex')}));
writeFileSync(`release/SHA256SUMS-${platform}-${arch}.txt`,checksums.map(item=>`${item.sha256}  ${basename(item.path)}`).join('\n')+'\n');
const manifest=artifactManifest({version:pkg.version,platform:platform==='win'?'win32':'darwin',arch,files:assets,baseUrl:base,notes:versionNotes(readFileSync('CHANGELOG.md','utf8'),pkg.version),signed});
writeFileSync(`release/release-${platform==='win'?'win32':'darwin'}-${arch}.json`,JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({version:pkg.version,platform,arch,signed,artifacts:assets,manifest:true}));
