import { useEffect, useState, type FormEvent } from 'react';
import { Check, CreditCard, ExternalLink, LockKeyhole, MapPin, Pencil, Plus, RefreshCw, Star, Trash2, X, Download, Upload } from 'lucide-react';
import type { AddressDraft, Card, HubAPI, LocalAddress, OfficialAddress, RegionOption } from './shared/types';

const blank = (): AddressDraft => ({label:'',recipient:'',phone:'',province:'',city:'',district:'',town:'',detail:'',postalCode:'',provinceId:'',cityId:'',districtId:'',townId:''});
const regionText = (a:AddressDraft) => [a.province,a.city,a.district,a.town].filter(Boolean).join(' ');
const phoneText = (phone:string) => `${phone.slice(0,3)} ${phone.slice(3,7).replace(/./g,'*')} ${phone.slice(-4)}`;

export default function AddressesPage({api,cards,isDemo,onMessage}:{api:HubAPI;cards:Card[];isDemo:boolean;onMessage:(text:string,error?:boolean)=>void}) {
  const [addresses,setAddresses]=useState<LocalAddress[]>([]);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [draft,setDraft]=useState<AddressDraft|null>(null),[editingId,setEditingId]=useState<string>();
  const [regions,setRegions]=useState<RegionOption[]>([]),[regionError,setRegionError]=useState('');
  const [towns,setTowns]=useState<RegionOption[]>([]),[townLoading,setTownLoading]=useState(false);
  const [thirdId,setThirdId]=useState('');
  const [cardId,setCardId]=useState(cards.find(c=>!c.archived)?.id||'');
  const [official,setOfficial]=useState<OfficialAddress[]|null>(null),[officialCard,setOfficialCard]=useState('');
  const [publishing,setPublishing]=useState<LocalAddress|null>(null),[makeDefault,setMakeDefault]=useState(false);
  const [deleting,setDeleting]=useState<LocalAddress|null>(null);
  const [backupMode,setBackupMode]=useState<'export'|'import'|null>(null);
  useEffect(()=>{let active=true;api.getAddresses().then(a=>{if(active)setAddresses(a);}).catch(e=>onMessage(String(e.message||e),true)).finally(()=>{if(active)setLoading(false);});api.getAddressRegions().then(a=>{if(active)setRegions(a);}).catch(()=>{if(active)setRegionError('地区暂时无法加载，可先填写文字地址本地保存；添加到官网时请重新选择地区。');});return()=>{active=false;};},[api]);
  useEffect(()=>{
    if(!thirdId){setTowns([]);setTownLoading(false);return;}
    let active=true;setTownLoading(true);setTowns([]);
    api.getAddressRegions(thirdId).then(options=>{
      if(!active)return;setTowns(options);setRegionError('');
      setDraft(previous=>{if(!previous)return previous;
        if(!options.length)return{...previous,districtId:'',townId:thirdId,town:''};
        const old=options.find(option=>option.id===previous.townId);
        return{...previous,districtId:thirdId,townId:old?.id||'',town:old?.name||''};
      });
    }).catch(()=>{if(active)setRegionError('街道信息读取失败，当前地址可本地保存；请刷新地区后再添加到官网。');}).finally(()=>{if(active)setTownLoading(false);});
    return()=>{active=false;};
  },[api,thirdId]);
  const run=async(work:()=>Promise<void>)=>{setBusy(true);try{await work();}catch(e){onMessage(e instanceof Error?e.message:String(e),true);}finally{setBusy(false);}};
  const edit=(address?:LocalAddress)=>{setDraft(address?{...address}:blank());setEditingId(address?.id);setThirdId(address?.districtId||(address?.town?'':address?.townId)||'');setRegionError(regions.length?'':regionError);};
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!draft)return;await run(async()=>{await api.saveAddress(draft,editingId);setAddresses(await api.getAddresses());setDraft(null);setThirdId('');onMessage('收货地址已在本地保存');});};
  const loadOfficial=()=>run(async()=>{if(!cardId)throw new Error('请先选择卡片');const data=await api.getOfficialAddresses(cardId);setOfficial(data);setOfficialCard(cardId);onMessage(`已读取该卡的 ${data.length} 个官网地址`);});
  const selectedCard=cards.find(c=>c.id===cardId);
  const provinces=regions;
  const cities=provinces.find(p=>p.id===draft?.provinceId)?.children||[];
  const districts=cities.find(p=>p.id===draft?.cityId)?.children||[];
  const patch=(value:Partial<AddressDraft>)=>setDraft(previous=>previous?{...previous,...value}:previous);
  const backup=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const passphrase=String(new FormData(event.currentTarget).get('passphrase')||'');await run(async()=>{if(backupMode==='export'){const ok=await api.exportAddresses(passphrase);onMessage(ok?'地址加密备份已保存':'已取消导出');}else{const data=await api.importAddresses(passphrase);if(data){setAddresses(data);onMessage('地址备份已恢复');}else onMessage('已取消恢复');}setBackupMode(null);});};
  return <div className="address-page">
    <div className="address-toolbar"><div><LockKeyhole size={17}/><span>{isDemo?'虚构地址演示，刷新后清空':'地址簿独立加密保存在这台电脑'}</span></div><div><button className="button secondary small" disabled={busy||isDemo} onClick={()=>setBackupMode('export')}><Download size={15}/>地址备份</button><button className="button secondary small" disabled={busy||isDemo} onClick={()=>setBackupMode('import')}><Upload size={15}/>恢复地址</button><button className="button primary" disabled={busy} onClick={()=>edit()}><Plus size={16}/>添加收货地址</button></div></div>
    {loading?<p className="muted-small">正在读取地址簿…</p>:addresses.length?<div className="address-grid">{addresses.map(a=><article className="address-card" key={a.id}><div className="address-card-head"><span className="address-icon"><MapPin size={20}/></span><div><h3>{a.label||'收货地址'}</h3><p>{a.recipient} · {phoneText(a.phone)}</p></div>{a.isDefault&&<span className="address-default">默认</span>}</div><p className="address-region">{regionText(a)}</p><p className="address-detail">{a.detail}</p>{a.postalCode&&<small>邮编 {a.postalCode}</small>}<div className="address-actions"><button disabled={busy||a.isDefault} onClick={()=>void run(async()=>{setAddresses(await api.setDefaultAddress(a.id));onMessage('本地默认地址已更新');})}><Star size={14}/>设为默认</button><button disabled={busy} onClick={()=>edit(a)}><Pencil size={14}/>编辑</button><button disabled={busy} onClick={()=>setDeleting(a)} aria-label={`删除地址 ${a.label||a.recipient}`}><Trash2 size={14}/>删除</button></div><button className="button secondary small address-publish" disabled={busy||isDemo||!cards.length} onClick={()=>{setPublishing(a);setMakeDefault(false);}}><CreditCard size={14}/>添加到指定卡的官网</button></article>)}</div>:<div className="empty-state"><span className="empty-icon"><MapPin size={28}/></span><h3>保存常用收货地址</h3><p>添加后可统一管理，也可以从卡片官网读取已有地址保存到本地。</p><button className="button primary" onClick={()=>edit()}><Plus size={16}/>添加第一个地址</button></div>}
    <section className="official-address-panel"><div className="section-heading"><div><h2>各卡官网地址</h2><p className="muted-small">官网地址按卡号独立保存。本地默认地址与官网默认地址分别管理。</p></div></div><div className="official-address-controls"><label className="select-control"><CreditCard size={15}/><select aria-label="选择地址来源卡片" value={cardId} onChange={e=>{setCardId(e.target.value);setOfficial(null);setOfficialCard('');}}>{!cards.length&&<option value="">请先添加卡片</option>}{cards.map(c=><option key={c.id} value={c.id}>{c.label} · {c.number}</option>)}</select></label><button className="button secondary small" disabled={busy||isDemo||!cardId} onClick={()=>void loadOfficial()}><RefreshCw size={15}/>读取官网地址</button><button className="button secondary small" disabled={busy||isDemo||!cardId} onClick={()=>void run(async()=>{await api.openCard(cardId,'addresses');onMessage('已打开该卡的官网地址管理');})}><ExternalLink size={15}/>官网地址管理</button></div>
    {official&&officialCard===cardId&&<div className="official-address-list">{!official.length?<p className="muted-small">这张卡暂无官网地址。可以先在本地添加地址，再选择此卡添加到官网。</p>:official.map(a=><article key={a.id}><div><strong>{a.draft.recipient} · {phoneText(a.draft.phone)} {a.isDefault&&<span className="address-default">官网默认</span>}</strong><p>{regionText(a.draft)} {a.draft.detail}</p></div><button className="button secondary small" disabled={busy} onClick={()=>void run(async()=>{await api.saveAddress(a.draft);setAddresses(await api.getAddresses());onMessage('官网地址已保存到本地地址簿');})}><Plus size={14}/>保存到本地</button></article>)}</div>}
    </section>
    {draft&&<div className="modal-backdrop"><section className="modal address-modal" role="dialog" aria-modal="true" aria-label={editingId?'编辑收货地址':'添加收货地址'}><div className="modal-head"><div><h2>{editingId?'编辑收货地址':'添加收货地址'}</h2><p>先保存在本地地址簿，添加到官网时再选择卡片并确认。</p></div><button className="icon-button" aria-label="关闭地址弹窗" disabled={busy} onClick={()=>{setDraft(null);setThirdId('');}}><X size={20}/></button></div><form onSubmit={event=>void save(event)}><label className="form-field">地址名称 <span>选填，例如家里、公司</span><input aria-label="地址名称" maxLength={30} value={draft.label} onChange={e=>patch({label:e.target.value})}/></label><div className="address-form-row"><label className="form-field">收货人<input aria-label="收货人" required minLength={2} maxLength={20} value={draft.recipient} onChange={e=>patch({recipient:e.target.value})}/></label><label className="form-field">手机号码<input aria-label="手机号码" required inputMode="tel" pattern="1[0-9]{10}" maxLength={11} value={draft.phone} onChange={e=>patch({phone:e.target.value})}/></label></div>
      {regions.length?<><div className="address-form-row regions"><label className="form-field">省份<select aria-label="地址省份" required value={draft.provinceId} onChange={e=>{const p=provinces.find(p=>p.id===e.target.value);patch({provinceId:p?.id||'',province:p?.name||'',cityId:'',city:'',districtId:'',district:'',townId:'',town:''});setThirdId('');}}><option value="">请选择省份</option>{provinces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="form-field">城市<select aria-label="地址城市" required value={draft.cityId} onChange={e=>{const p=cities.find(p=>p.id===e.target.value);patch({cityId:p?.id||'',city:p?.name||'',districtId:'',district:'',townId:'',town:''});setThirdId('');}}><option value="">请选择城市</option>{cities.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="form-field">区县<select aria-label="地址区县" required value={thirdId} onChange={e=>{const p=districts.find(p=>p.id===e.target.value);patch({districtId:p?.id||'',district:p?.name||'',townId:'',town:''});setThirdId(p?.id||'');}}><option value="">请选择区县</option>{districts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{(towns.length>0||townLoading)&&<label className="form-field">街道 / 乡镇<select aria-label="地址街道" disabled={townLoading} required={towns.length>0} value={draft.townId} onChange={e=>{const p=towns.find(p=>p.id===e.target.value);patch({townId:p?.id||'',town:p?.name||''});}}><option value="">{townLoading?'正在读取街道…':'请选择街道或乡镇'}</option>{towns.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}</>:<div className="address-form-row regions">{(['province','city','district'] as const).map((key,i)=><label className="form-field" key={key}>{['省份','城市','区县'][i]}<input required value={draft[key]} onChange={e=>patch({[key]:e.target.value,provinceId:'',cityId:'',districtId:'',townId:'',town:''})}/></label>)}</div>}
      {regionError&&<p className="address-warning">{regionError}</p>}<label className="form-field">详细地址<input aria-label="详细地址" required minLength={2} maxLength={100} value={draft.detail} placeholder="街道门牌号、楼栋、单元和房间号" onChange={e=>patch({detail:e.target.value})}/></label><label className="form-field">邮政编码 <span>选填</span><input aria-label="邮政编码" maxLength={6} inputMode="numeric" pattern="[0-9]{6}|" value={draft.postalCode} onChange={e=>patch({postalCode:e.target.value})}/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>{setDraft(null);setThirdId('');}}>取消</button><button className="button primary" disabled={busy||townLoading}><Check size={16}/>保存本地地址</button></div></form></section></div>}
    {publishing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="确认添加官网地址"><div className="modal-head"><div><h2>添加到指定卡的官网</h2><p>将以下收货信息发送给所选卡片的关爱通地址簿。</p></div><button className="icon-button" aria-label="关闭官网地址确认" disabled={busy} onClick={()=>setPublishing(null)}><X size={20}/></button></div><label className="form-field">目标卡片<select aria-label="添加地址的目标卡片" value={cardId} onChange={e=>setCardId(e.target.value)}>{cards.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.label} · {c.number}</option>)}</select></label><div className="address-confirm-details"><strong>{publishing.recipient} · {publishing.phone}</strong><p>{regionText(publishing)} {publishing.detail}</p><small>目标卡号：{selectedCard?.number||'请选择可用卡片'}</small></div><label className="address-checkbox"><input type="checkbox" checked={makeDefault} onChange={e=>setMakeDefault(e.target.checked)}/>将新增地址设为该卡官网默认地址</label><p className="muted-small">重复地址会先检查。企业固定配送等特殊地址规则会交由官网处理。本操作只添加地址。</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPublishing(null)}>取消</button><button className="button primary" disabled={busy||!selectedCard||selectedCard.archived} onClick={()=>void run(async()=>{const result=await api.publishAddress(cardId,publishing.id,makeDefault);setPublishing(null);setOfficial(null);onMessage(result.created?'收货地址已添加到所选卡片官网':'该卡官网已存在相同地址，已保留原默认设置');})}><Check size={16}/>确认添加官网地址</button></div></section></div>}
    {deleting&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="删除本地地址"><div className="modal-head"><h2>删除本地地址</h2><button className="icon-button" disabled={busy} onClick={()=>setDeleting(null)}><X size={20}/></button></div><p>删除“{deleting.label||deleting.recipient}”后，可从地址备份恢复。官网地址仍保留。</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setDeleting(null)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void run(async()=>{setAddresses(await api.removeAddress(deleting.id));setDeleting(null);onMessage('本地地址已删除');})}>删除本地地址</button></div></section></div>}
    {backupMode&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="地址加密备份"><div className="modal-head"><div><h2>{backupMode==='export'?'备份收货地址':'恢复收货地址'}</h2><p>{backupMode==='export'?'地址备份独立于卡片备份，使用你设置的口令加密。':'恢复将替换当前本地地址簿，官网地址不变。'}</p></div><button className="icon-button" disabled={busy} onClick={()=>setBackupMode(null)}><X size={20}/></button></div><form onSubmit={event=>void backup(event)}><label className="form-field">备份口令<input name="passphrase" type="password" required minLength={8} autoComplete="new-password"/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setBackupMode(null)}>取消</button><button className="button primary" disabled={busy}>{backupMode==='export'?'保存加密备份':'选择备份并恢复'}</button></div></form></section></div>}
  </div>;
}
