import { useEffect,useState } from 'react';
import { ChevronDown,Heart,Layers,LoaderCircle,Package,Search,X } from 'lucide-react';
import type { AppState,HubAPI,Product,ProductOffer } from './shared/types';
import { DEFAULT_PRODUCT_QUERY,type ProductPage,type ProductQuery } from './shared/operations';
import { matchingPriceOffers } from './shared/price-filter';
import { sourceCategories } from './shared/queries';
import PriceFilter from './PriceFilter';
import VirtualProductGrid from './VirtualProductGrid';

export default function CatalogPage({api,state,revision,onSelect,onMessage,onState,initialCardId='all'}:{api:HubAPI;state:AppState;revision:number;initialCardId?:string;onSelect:(product:Product,offers:ProductOffer[])=>void;onMessage:(message:string,error?:boolean)=>void;onState:(state:AppState)=>void}){
  const [query,setQuery]=useState<ProductQuery>({...structuredClone(DEFAULT_PRODUCT_QUERY),cardId:initialCardId});
  const [data,setData]=useState<ProductPage|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const [merge,setMerge]=useState(false),[selected,setSelected]=useState<string[]>([]);
  const key=JSON.stringify(query);
  const update=(patch:Partial<ProductQuery>)=>setQuery(previous=>({...previous,...patch,page:patch.page??1}));
  useEffect(()=>update({cardId:initialCardId}),[initialCardId]);
  useEffect(()=>{let current=true;setLoading(true);setError('');const timer=setTimeout(()=>void api.queryProducts(query).then(result=>{if(current){setData(result);if(query.page>1&&!result.items.length&&result.total)update({page:Math.max(1,Math.ceil(result.total/query.pageSize))});}}).catch(error=>{if(current)setError(error instanceof Error?error.message:String(error));}).finally(()=>{if(current)setLoading(false);}),150);return()=>{current=false;clearTimeout(timer);};},[api,key,revision]);
  const mutate=async(work:()=>Promise<AppState>)=>{try{onState(await work());return true;}catch(error){onMessage(error instanceof Error?error.message:String(error),true);return false;}};
  const prices=(product:Product)=>matchingPriceOffers(product,query.cardId,query.price,offer=>query.category==='全部分类'||sourceCategories(product,offer).includes(query.category));
  return <><div className="product-toolbar"><label className="search-input"><Search size={17}/><input value={query.search} aria-label="搜索商品" placeholder="搜索商品、品牌或规格" onChange={event=>update({search:event.target.value})}/>{query.search&&<button aria-label="清空搜索" onClick={()=>update({search:''})}><X size={14}/></button>}</label><label className="select-control"><select value={query.cardId} aria-label="商品卡片筛选" onChange={event=>update({cardId:event.target.value})}><option value="all">全部卡片</option>{state.cards.map(card=><option key={card.id} value={card.id}>{card.label} · {card.number.slice(-4)}</option>)}</select><ChevronDown size={14}/></label><button className={`button secondary ${query.favoritesOnly?'selected':''}`} onClick={()=>update({favoritesOnly:!query.favoritesOnly})}><Heart size={15}/>我的收藏</button><button className="button secondary" onClick={()=>{setMerge(!merge);setSelected([]);}}><Layers size={15}/>{merge?'结束整理':'整理同款'}</button></div>
    <PriceFilter value={query.price} onChange={price=>update({price})} units={data?.units??[]} amounts={data?.amounts??[]}/>
    <div className="catalog-layout"><aside className="catalog-categories" aria-label="商品分类"><div className="catalog-categories-head"><h2>商品分类</h2><p>按卡片与兑换额度统计</p></div><div className="catalog-category-list">{data?.categories.map(item=><button key={item.name} className={query.category===item.name?'active':''} aria-pressed={query.category===item.name} onClick={()=>update({category:item.name})}><span>{item.name}</span><b>{item.count}</b></button>)}</div></aside><section className="catalog-results" aria-label="筛选商品结果"><div className="catalog-results-head"><h2>{query.category}<span>{data?.total??0} 件</span></h2><button className="text-link" onClick={()=>setQuery(structuredClone(DEFAULT_PRODUCT_QUERY))}>清除筛选</button></div>
      {merge&&<div className="merge-banner"><span>已选 {selected.length} 件；来源报价将保留。</span><button className="button primary small" disabled={selected.length<2||loading} onClick={()=>void mutate(()=>api.mergeProducts(selected)).then(ok=>{if(ok){setSelected([]);setMerge(false);}})}>合并选中商品</button></div>}
      {error&&<p className="text-error" role="alert">{error}</p>}{loading&&<p className="muted-small" role="status"><LoaderCircle size={16} className="spin"/>正在查询…</p>}
      {!error&&data?.items.length?<VirtualProductGrid items={data.items} resetKey={key} renderItem={product=>{
        const offers=prices(product),available=offers.filter(offer=>{const card=state.cards.find(card=>card.id===offer.cardId);return card&&!card.archived&&!['expired','exhausted'].includes(card.status)&&offer.stock!==0;});
        const known=available.filter(offer=>offer.price!==null),units=new Set(known.map(offer=>offer.priceUnit));
        const label=!available.length?'暂无可兑换来源':units.size>1?'多种兑换单位':known.length?`${Math.min(...known.map(offer=>offer.price!))} ${known[0].priceUnit}`:'官网确认价格';
        return <article key={product.id} className={`product-tile ${selected.includes(product.id)?'selected':''}`}><div className="product-visual"><button className="product-open" aria-label={`查看 ${product.name}`} onClick={()=>onSelect(product,offers)}>{product.image?<img src={product.image} alt="" loading="lazy"/>:<Package size={48}/>}</button><span className="offer-badge">{new Set(product.offers.map(offer=>offer.cardId)).size} 张来源卡</span>{merge?<input className="merge-checkbox" type="checkbox" aria-label={`选择 ${product.name} 合并`} checked={selected.includes(product.id)} onChange={()=>setSelected(previous=>previous.includes(product.id)?previous.filter(id=>id!==product.id):[...previous,product.id])}/>:<button className={`favorite-button ${product.favorite?'favorited':''}`} aria-label={`${product.favorite?'取消收藏':'收藏'} ${product.name}`} onClick={()=>void mutate(()=>api.favoriteProduct(product.id))}><Heart size={17} fill={product.favorite?'currentColor':'none'}/></button>}</div><div className="product-info"><p className="product-category">{product.category}</p><button className="product-name-button" onClick={()=>onSelect(product,offers)}>{product.name}</button><p className="product-spec">{product.specification||'官网确认规格'}</p><strong className="product-price">{label}</strong></div></article>;
      }}/>:!loading&&!error&&<div className="empty-state"><Package size={32}/><h3>暂无匹配商品</h3><p>调整卡片、分类、关键词或兑换额度。</p></div>}
      <div className="pagination"><button className="button secondary small" disabled={query.page===1||loading} onClick={()=>update({page:query.page-1})}>上一页</button><span>第 {query.page} / {Math.max(1,Math.ceil((data?.total??0)/query.pageSize))} 页</span><button className="button secondary small" disabled={loading||query.page*query.pageSize>=(data?.total??0)} onClick={()=>update({page:query.page+1})}>下一页</button><select aria-label="每页商品数" value={query.pageSize} onChange={event=>update({pageSize:Number(event.target.value)})}>{[24,60,100].map(size=><option key={size} value={size}>{size} 件/页</option>)}</select></div>
    </section></div></>;
}
