import { useEffect,useState } from 'react';
import type { AppState,HubAPI } from './shared/types';
import { DEFAULT_ORDER_QUERY,type OrderPage,type OrderQuery } from './shared/operations';

export default function OrdersPage({api,state,revision,onMessage}:{api:HubAPI;state:AppState;revision:number;onMessage:(text:string,error?:boolean)=>void}){
  const [query,setQuery]=useState<OrderQuery>(structuredClone(DEFAULT_ORDER_QUERY)),[data,setData]=useState<OrderPage|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const update=(patch:Partial<OrderQuery>)=>setQuery(previous=>({...previous,...patch,page:patch.page??1}));
  useEffect(()=>{let current=true;setLoading(true);setError('');const timer=setTimeout(()=>void api.queryOrders(query).then(result=>{if(current)setData(result);}).catch(error=>{if(current)setError(error.message);}).finally(()=>{if(current)setLoading(false);}),150);return()=>{current=false;clearTimeout(timer);};},[api,JSON.stringify(query),revision]);
  return <><div className="order-filters"><input aria-label="搜索订单" placeholder="搜索商品、订单号或物流" value={query.search} onChange={event=>update({search:event.target.value})}/><select aria-label="订单卡片筛选" value={query.cardId} onChange={event=>update({cardId:event.target.value})}><option value="all">全部卡片</option>{state.cards.map(card=><option key={card.id} value={card.id}>{card.label} · {card.number.slice(-4)}</option>)}</select><select aria-label="订单状态筛选" value={query.status} onChange={event=>update({status:event.target.value})}><option value="all">全部状态</option>{data?.statuses.map(status=><option key={status}>{status}</option>)}</select><label>从 <input type="date" aria-label="订单开始日期" value={query.from} onChange={event=>update({from:event.target.value})}/></label><label>至 <input type="date" aria-label="订单结束日期" value={query.to} onChange={event=>update({to:event.target.value})}/></label><button className="button secondary" onClick={()=>void api.exportOrders(query).then(saved=>onMessage(saved?'筛选订单已脱敏导出':'已取消导出')).catch(error=>onMessage(error.message,true))}>导出筛选订单</button></div>
    <p className="muted-small">{data?.total??0} 条已同步记录{loading?' · 正在查询…':''}</p>{error&&<p className="text-error" role="alert">{error}</p>}
    <div className="order-list">{data?.items.map(order=>{const card=state.cards.find(card=>card.id===order.cardId);return <article key={order.id} className="order-record"><div><h3>{order.name}</h3><p>{card?.label} · 卡尾号 {card?.number.slice(-4)} · {order.sourceId}</p><p>{order.createdAt?new Date(order.createdAt).toLocaleString('zh-CN'):'日期未知'}{order.tracking?` · 物流 ${order.tracking}`:''}</p></div><div><strong>{order.status}</strong><p>{order.amount===null?'金额未知':order.amount}</p><button className="button secondary small" onClick={()=>void api.openCard(order.cardId,'orders').catch(error=>onMessage(error.message,true))}>官网订单</button></div></article>;})}</div>
    {!data?.items.length&&!loading&&<div className="empty-state"><h3>暂无匹配订单</h3></div>}<div className="pagination"><button className="button secondary small" disabled={loading||query.page===1} onClick={()=>update({page:query.page-1})}>上一页</button><span>第 {query.page} / {Math.max(1,Math.ceil((data?.total??0)/query.pageSize))} 页</span><button className="button secondary small" disabled={loading||query.page*query.pageSize>=(data?.total??0)} onClick={()=>update({page:query.page+1})}>下一页</button></div></>;
}
