import { useEffect,useState } from 'react';
import type { HubAPI,AppState } from './shared/types';
import type { PreparedUpdate,UpdateInfo,UpdateProgress } from './shared/operations';
import { DEFAULT_UPDATE_FEED } from './shared/release-config';
export default function ReleasePanel({api,state,onState,onMessage}:{api:HubAPI;state:AppState;onState:(state:AppState)=>void;onMessage:(text:string,error?:boolean)=>void}){
  const [feed,setFeed]=useState(state.settings.updateFeed??''),[info,setInfo]=useState<UpdateInfo|null>(null),[busy,setBusy]=useState(false);
  const [preparing,setPreparing]=useState(false),[prepared,setPrepared]=useState<PreparedUpdate|null>(null),[progress,setProgress]=useState<UpdateProgress|null>(null);
  useEffect(()=>api.onUpdateProgress(setProgress),[api]);
  const check=async()=>{setBusy(true);setInfo(null);setPrepared(null);setProgress(null);try{onState(await api.updateSettings({updateFeed:feed.trim()}));setInfo(await api.checkUpdates());}catch(error){onMessage(error instanceof Error?error.message:String(error),true);}finally{setBusy(false);}};
  const prepare=async()=>{setBusy(true);setPreparing(true);setPrepared(null);setProgress(null);try{setPrepared(await api.prepareUpdate());onMessage('安装包已校验，当前数据库已备份');}catch(error){setProgress(null);onMessage(error instanceof Error&&error.name==='AbortError'?'已取消下载':error instanceof Error?error.message:String(error),true);}finally{setBusy(false);setPreparing(false);}};
  const status=info?.status==='unpublished'?'暂未发布正式版本':info?.status==='unsupported'?'当前系统暂无安装包':info?.available?`可更新至 v${info.version}`:`当前版本 v${info?.currentVersion??''} 已是最新`;
  return <section className="settings-panel release-panel"><h2>程序更新</h2><p>默认检查项目 GitHub Releases。下载安装包并校验后备份数据，由你确认打开更新包。</p><details><summary>自定义更新来源</summary><label className="form-field">HTTPS 发布地址<input type="url" value={feed} placeholder={DEFAULT_UPDATE_FEED} disabled={busy} onChange={event=>{setFeed(event.target.value);setInfo(null);setPrepared(null);}}/></label><button className="text-link" disabled={busy} onClick={()=>{setFeed('');setInfo(null);setPrepared(null);}}>恢复默认 GitHub 来源</button></details><button className="button secondary" disabled={busy} onClick={()=>void check()}>{busy&&!preparing?'正在检查…':'检查更新'}</button>{info&&<div className="release-result"><strong>{status}</strong><p className="release-notes">{info.notes}</p>{progress&&<div className="update-progress" role="status"><p>{progress.phase==='downloading'?`已下载 ${(progress.downloaded/1048576).toFixed(1)} MB${progress.total===null?'':` / ${(progress.total/1048576).toFixed(1)} MB`}`:progress.phase==='verifying'?'正在校验安装包':progress.phase==='backing-up'?'正在备份当前数据库':'安装包已准备好'}</p>{progress.total&&<progress max={progress.total} value={progress.downloaded}/>}</div>}{info.available&&!prepared&&<button className="button primary" disabled={busy} onClick={()=>void prepare()}>下载校验并备份</button>}{preparing&&<button className="button secondary" onClick={()=>void api.cancelUpdate().catch(error=>onMessage(error.message,true))}>取消下载</button>}{prepared&&<div><p>SHA-256 校验通过，升级前备份已保存。打开后将退出当前程序；macOS 请将解压后的应用替换到应用目录。</p><button className="button primary" disabled={busy} onClick={()=>{setBusy(true);void api.installUpdate().catch(error=>{onMessage(error.message,true);setBusy(false);});}}>打开已校验更新包并退出</button></div>}</div>}</section>;
}
